/usr/bin/cadence

/etc/xdg/autostart/cadence-session-start.desktop

/usr/share/icons/hicolor/scalable/apps/cadence.svg
/usr/share/icons/hicolor/48x48/apps/cadence.png
/usr/share/icons/hicolor/16x16/apps/cadence.png
/usr/share/icons/hicolor/256x256/apps/cadence.png
/usr/share/icons/hicolor/128x128/apps/cadence.png

/usr/share/cadence/src/ui_cadence_tb_jack.py
/usr/share/cadence/src/cadence.py
/usr/share/cadence/src/ui_cadence_tb_pa.py
/usr/share/cadence/src/ui_cadence_rwait.py
/usr/share/cadence/src/ui_cadence_tb_a2j.py
/usr/share/cadence/src/ui_cadence_tb_alsa.py
/usr/share/cadence/src/ui_cadence.py

/usr/share/applications/cadence.desktop
