/usr/bin/catarina

/usr/share/icons/hicolor/scalable/apps/catarina.svg
/usr/share/icons/hicolor/48x48/apps/catarina.png
/usr/share/icons/hicolor/16x16/apps/catarina.png
/usr/share/icons/hicolor/256x256/apps/catarina.png
/usr/share/icons/hicolor/128x128/apps/catarina.png

/usr/share/cadence/src/catarina.py
/usr/share/cadence/src/ui_catarina_addport.py
/usr/share/cadence/src/ui_catarina.py
/usr/share/cadence/src/ui_catarina_renameport.py
/usr/share/cadence/src/ui_catarina_addgroup.py
/usr/share/cadence/src/ui_catarina_connectports.py
/usr/share/cadence/src/ui_catarina_removegroup.py
/usr/share/cadence/src/ui_catarina_renamegroup.py
/usr/share/cadence/src/ui_catarina_disconnectports.py
/usr/share/cadence/src/ui_catarina_removeport.py

/usr/share/applications/catarina.desktop
